carts/urls.py
   
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import checkout

router = routers.DefaultRouter()
router.register('', views.CartViewSet)
router.register('delivery-cost', views.DeliveryCostViewSet)

urlpatterns = [
    path('checkout',checkout, name="checkout"),
    path('', include((router.urls, 'shopping_cart_api.cart'))),
]

easydrink/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
   openapi.Info(
      title="Easy Drink",
      default_version='v1',
      description="Easy drink application",
    #   terms_of_service="https://www.google.com/policies/terms/",
    #   contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Documentation
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


    #API endpoints
    path('api/v1/auth/', include ('users.urls')),
    path('api/v1/products/', include('products.urls')),
    path('api/v1/carts/', include('carts.urls')), 
    path('api/v1/discounts/', include('discounts.urls')), 
    path('api/v1/search/', include("search.urls")),
    

    #frontend
    path('', include('pages.urls'))

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from .views import buy, get_products_category, AboutPageView, ContactsPageView, WishesPageView, OrdersPageView, LoginCartPageView,  home_page, get_cart, get_products, get_product_detail, post_register, post_reset_password, post_login,template_payment,favorite_products, about_us

app_name = "pages"

urlpatterns = [
    path("", home_page, name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("wishes/", WishesPageView.as_view(), name="wishes"),
    path("orders/", OrdersPageView.as_view(), name="orders"),
    path("login_cart/",  LoginCartPageView.as_view(), name="login_cart"),
    path("products/", get_products, name="products"),
    path(r'products/category/<str:id>/', get_products_category, name='products_category'),
    path("products/<str:pk>/",get_product_detail, name="product_detail"),
    path("product-buy/",buy, name="buy"),
    path("cart/", get_cart, name="cart"),
    path("login/", post_login, name="login"),
    path("register/", post_register, name="register"),
    path("reset-password/", post_reset_password, name="reset-password"),
    path("payments/",template_payment, name="payments"),
    path("favorites/",favorite_products, name="favorites"),
    path("about_us/", about_us, name="about_us"),
    ]

carts/models.py
# import uuid   
from django.db import models
from django.db.models.deletion import CASCADE
from products.models import Product
from users.models import User
from django.urls import reverse

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 100)]
class Cart(models.Model):
    # id = models.UUIDField(default=uuid.uuid4, unique=True, 
    #                             primary_key=True, editable=False
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    item = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField( choices=PRODUCT_QUANTITY_CHOICES,
                                    default=PRODUCT_QUANTITY_CHOICES 
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} - {} - {} - {}".format(self.user,
                                               self.item,
                                               self.quantity,
                                               self.created_at,
                                               self.updated_at)
    def get_absolute_url(self):
       return reverse("carts:list_by_user", kwargs={"slug": self.slug})

class DeliveryCost(models.Model):
    status = models.CharField(max_length=7,
                              choices=(('Active', 'active'), ('Passive', 'passive')),
                              default="passive",
                              null=False)
    cost_per_delivery = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    cost_per_product = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    fixed_cost = models.DecimalField(max_digits=10, decimal_places=2, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} - {} - {} - {} - {} - {}".format(self.status,
                                                    self.cost_per_delivery,
                                                    self.cost_per_product,
                                                    self.fixed_cost,
                                                    self.created_at,
                                                    self.updated_at)

carts/views.py
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import Token
from .models import Cart, DeliveryCost
from .serializers import CartSerializer, DeliveryCostSerializer
from .helpers import CartHelper
from users.models import User 
from rest_framework.decorators import api_view, permission_classes
from rest_framework import viewsets, permissions
from easydrink import local_settings
import jwt


def get_id_by_token(request):
    secret_key = local_settings.SECRET_KEY
    header_token = request.META['HTTP_AUTHORIZATION'].replace('Bearer ', '')
    payload = jwt.decode(jwt=header_token, key=secret_key, algorithms=['HS256'])
    return  payload['user_id']
    

#filtro pra criar uma excessão de busca, no caso trazer itens dos carrinhos de um único usuário
@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def checkout(request):

    userID = get_id_by_token(request)

    try:
        user = User.objects.get(pk=userID)
    except Exception as e:
        return Response(status=status.HTTP_404_NOT_FOUND,
                        data={'Error': str(e)})

    cart_helper = CartHelper(user)
    checkout_details = cart_helper.prepare_cart_for_checkout()

    if not checkout_details:
        return Response(status=status.HTTP_404_NOT_FOUND,
                        data={'error': 'Cart of user is empty.'})

    return Response(status=status.HTTP_200_OK, data={'checkout_details': checkout_details})

    

# @permission_classes([permissions.IsAuthenticated])
class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.all().order_by('id')
    serializer_class = CartSerializer

class DeliveryCostViewSet(viewsets.ModelViewSet):
    queryset = DeliveryCost.objects.all().order_by('id')
    serializer_class = DeliveryCostSerializer

templates/cart/cart_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}My cart{% endblock title %}




{% block content %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

<style>
    body{
        margin-top: 85px;
    }
    .card{
        margin-top: 50px;
    }
    .card-body-1{
        margin-top: 20px;
    }
</style>

<body>
    
<div class="row">
    {% if cart %}
        <aside class="col-lg-9">
            <div class="table-reponsive">
                <table class="table ">
                    <thead>
                        <tr class="small text-uppercase">
                            <th>Products</th>
                            <th style="text-align: center;">Quantity</th>
                            <th>Unit Price</th>
                            <th>Total Price</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for product in cart.products %}
                        <tr class="products">
                            <td>
                                <figure class="row align-items-center">
                                    <div class="col-auto">
                                    <a href="{{product.get_absolute_url}}">
                                        <img src={{product.product_image}}
                                            width="60" alt="Product" >
                                    </a>
                                    </div>
                                    <figcaption class="info col-auto">
                                        <label class="text-dark"  href="{{ product.get_absolute_url }}" data-abc="true">
                                            <a href="{{product.get_absolute_url}}">{{ product.product_name|slice:'15'}}</a>
                                        </label>
                                        <p class="text-muted small">
                                            <a href="{% url 'pages:products_category' product.category_id %}">
                                                {{product.category_name}}
                                                <br>
                                            </a>
                                        </p>
                                    </figcaption>
                                </figure>
                            </td>
                            <td>
                                <div class="update-cart">
                                    <form  method="post" class="update-cart">
                                        {% csrf_token %}
                                            <button name="decrease_product_quantity" class="btn-product-quantity" type="submit" value="{{ product.cart_id }}">
                                                <i data-feather="chevron-left"></i>
                                            </button>

                                            <input type="text" readonly class="form-control input-quantity" placeholder="Quantity" style="text-align:center"
                                                value={{ product.quantity }}>
            
                                            <button name="increase_product_quantity" class="btn-product-quantity" type="submit" value="{{ product.cart_id }}">
                                                <i data-feather="chevron-right"></i>
                                            </button>
                                    </form>
                                </div>
                            </td>
                            <td>
                                <div class="price-wrap">
                                    <p class="price">
                                        R$ {{ product.unit_price }}
                                    </p>
                                </div>
                            </td>
                                                        <td>
                                <div class="price-wrap">
                                    <p class="price">
                                        R$ {{ product.product_total_price }}
                                    </p>
                                </div>
                            </td>
                            <td>
                                <div class="d-flex justify-content-end align-items-center" style="min-height: 100%;">
                                    <form  method="post">
                                    {% csrf_token %}
                                        <button name="delete" class="btn-product-remove" type="submit" value="{{ product.cart_id }}">
                                        <i data-feather="trash"></i>
                                        </button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                    {% endfor %}   
                    </tbody>
                </table>
            </div>
        </aside>
        <aside class="col-sm-12 col-lg-3 h4">
            <div class="card md-3 box-coupon">
                <div class="card-body-1">
                    <div class="form-group">
                        <label class="items">Have Coupon?</label>
                        <div class="input-group">
                            <input type="text" class="form-control coupon input-size" name placeholder="coupon code" />
                            <span class="input-group-append">
                                <button class="btn btn-apply">Apply</button>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card box-coupon">
                <div class="card-body">
                    <dl class="row">
                    {% for total in cart.total %}
                        <div class="col-auto d-flex">
                            <dt>Total Price: </dt>
                            <dd class="text-right text-dark b ml-3">R$ {{ total.total_price }}</dd>
                        </div>
                    {% endfor %}
                    </dl>

                    <dl class="row">
                    {% for total in cart.total %}
                        <div class="col-auto d-flex">
                            <dt>Discount:</dt>
                            <dd class="text-right text-danger ml-3 ">
                                - R${{ total.total_discount }}
                            </dd>
                        </div>
                         {% endfor %}
                    </dl>
                    
                    <dl class="row">
                    {% for amount in cart.amount %}
                        <div class="col-auto d-flex">
                            <dt>Total:</dt>
                            <dd class="text-right text-dark b ml-3">
                                <strong> R$ {{ amount.total_amount }}</strong>
                            </dd>
                        </div>
                    {% endfor %}
                    </dl>

                    <hr>
                    <div class="row">
                        <div class="col-6">
                            <a href="{% url 'pages:products' %}" class="btn btn-checkout" style="width: 70px;"
                                data-abc="true">Continue shopping</a>
                        </div>
                        <div class="col-6">
                            <a href="{% url 'pages:payments' %}" class="btn btn-checkout btn-finish" data-abc="true" style="width: 70px;">
                                Check Purchases</a>
                        </div>


                    </div>
                </div>
            </div>
        </aside>
    {% else %}
        <p>Unfortunately your cart is still empty! :( </p>
    {% endif %}    
</div>
</body>



{% endblock content %}