carts/urls.py
   
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import checkout

router = routers.DefaultRouter()
router.register('', views.CartViewSet)
router.register('delivery-cost', views.DeliveryCostViewSet)

urlpatterns = [
    path('checkout',checkout, name="checkout"),
    path('', include((router.urls, 'shopping_cart_api.cart'))),
]

easydrink/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
   openapi.Info(
      title="Easy Drink",
      default_version='v1',
      description="Easy drink application",
    #   terms_of_service="https://www.google.com/policies/terms/",
    #   contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Documentation
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


    #API endpoints
    path('api/v1/auth/', include ('users.urls')),
    path('api/v1/products/', include('products.urls')),
    path('api/v1/carts/', include('carts.urls')), 
    path('api/v1/discounts/', include('discounts.urls')), 
    path('api/v1/search/', include("search.urls")),
    

    #frontend
    path('', include('pages.urls'))

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.urls import path

app_name = "search"

from .views import (
                        SearchProductView, 
                    )

urlpatterns = [
    path('', SearchProductView.as_view(), name='query'),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from products.models import Product
from services import products_service


class SearchProductView(ListView):
    template_name = "search/result_query.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        query = self.request.GET.get('q')

        if query is not None:
            request = self.request
            products = products_service.get_products_search(request, query)
            context['products'] = products
            
        context['query'] = query
        return context

    def get_queryset(self, *args, **kargs):
        request = self.request
        result = request.GET
        query = result.get('q', None)  # result['q']
        if query is not None:
            products = products_service.get_products_search(request, query)
            return render(request, "search/result_query.html", context={'query': query, 'products': products})
        products = products_service.get_products(request)
        return render(request, "search/result_query.html", context={'query': query, 'products': products})

templates/search/result_query.html
{% extends "base/base.html" %}

{% block content %} 

<div class='row mb-3' style="margin-top: 10rem">
    {% if query %}
    <div class='col-12'>
        <h1>Resultado para <b class="text-danger">"{{ query }} "</b></h1>
        <hr />
    </div>
    {% else %}
    <div class='col-12 col-md-8 mx-auto py-5'>
        {% include 'search/search_form.html' %}
    </div>
    <div class='col-12'>
        <hr>
    </div>
    {% endif %}
   <section class="section-products" style="
    background: none;
">
  <div class="row" style="background: none;">
  <div class="container">
      <div class="row">
          <!-- Single Product -->
          <div class="row">
            {% for product in products %}
              <div id="product-1" class="single-product col-md-4">
                  <div class="part-1" style="background: url('{{product.image}}') no-repeat center;">
                      <ul>
                          <li><a href="{{ product.my_absolute_url }}"><i class="fas fa-shopping-cart"></i></a></li>
                          <li><a href="#"><i class="fas fa-heart"></i></a></li>
                          <li><a href="#"><i class="fas fa-plus"></i></a></li>
                          <li><a href="{{ product.my_absolute_url }}"><i class="fas fa-expand"></i></a></li>
                      </ul>
                  </div>
                  <div class="part-2">
                      <h3 class="product-title">
                        <a href="{{ product.my_absolute_url }}">{{product.title}}</a>
                      </h3>
                    {% if product.old_price %}
                      <h4 class="product-old-price">$ {{product.old_price}}</h4>
                    {% endif %}
                      <h4 class="product-price"> $ {{product.price}}</h4>
                  </div>
              </div>
              {%endfor%}
          </div>
      </div>
  </div>
</section>
{% endblock content%}

templates/search/search_form.html
<form method='GET' action='{% url "search:query" %}' class="form my-2 my-lg-0" id="search-form">
  <div class="input_group">
    <input class="form-control" style="border:transparent;"
    type="search"
    placeholder="Search Here ..."
    name='q'
    aria-label="Search"
    id="search-box"
    value='{{ request.GET.q }}'
    />
  </div>
  <label for="search-box" class="fas fa-search"></label>
  <i class="fa fa-times" id="close" aria-hidden="true"></i>
</form>