carts/urls.py
   
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import checkout

router = routers.DefaultRouter()
router.register('', views.CartViewSet)
router.register('delivery-cost', views.DeliveryCostViewSet)

urlpatterns = [
    path('checkout',checkout, name="checkout"),
    path('', include((router.urls, 'shopping_cart_api.cart'))),
]

easydrink/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
   openapi.Info(
      title="Easy Drink",
      default_version='v1',
      description="Easy drink application",
    #   terms_of_service="https://www.google.com/policies/terms/",
    #   contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Documentation
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


    #API endpoints
    path('api/v1/auth/', include ('users.urls')),
    path('api/v1/products/', include('products.urls')),
    path('api/v1/carts/', include('carts.urls')), 
    path('api/v1/discounts/', include('discounts.urls')), 
    path('api/v1/search/', include("search.urls")),
    

    #frontend
    path('', include('pages.urls'))

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from .views import buy, get_products_category, AboutPageView, ContactsPageView, WishesPageView, OrdersPageView, LoginCartPageView,  home_page, get_cart, get_products, get_product_detail, post_register, post_reset_password, post_login,template_payment,favorite_products, about_us

app_name = "pages"

urlpatterns = [
    path("", home_page, name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("wishes/", WishesPageView.as_view(), name="wishes"),
    path("orders/", OrdersPageView.as_view(), name="orders"),
    path("login_cart/",  LoginCartPageView.as_view(), name="login_cart"),
    path("products/", get_products, name="products"),
    path(r'products/category/<str:id>/', get_products_category, name='products_category'),
    path("products/<str:pk>/",get_product_detail, name="product_detail"),
    path("product-buy/",buy, name="buy"),
    path("cart/", get_cart, name="cart"),
    path("login/", post_login, name="login"),
    path("register/", post_register, name="register"),
    path("reset-password/", post_reset_password, name="reset-password"),
    path("payments/",template_payment, name="payments"),
    path("favorites/",favorite_products, name="favorites"),
    path("about_us/", about_us, name="about_us"),
    ]

templates/about.html
{% extends 'base/base_home.html' %}

{% block title %}About Us{% endblock title %}

{% block content %}
{%load static%}


<section class="about" id="about">

    <h3 class="sub-heading"> about us </h3>
    <h1 class="heading"> why choose us? </h1>

    <div class="row">

        <div class="image">
            <img src="{% static 'images/Logo3.png'%}" alt="logo">
        </div>

        <div class="content" style="text-transform: none">
            <h3>Best Beverage's Delivery</h3>
            <p >We are here to provide a new delivey system for you. Where you can order & chill while waiting the beverage. We deliver the party at your own very  cozy home</p>
            <p>Come try out our delivey system</p>
            <div class="icons-container">
                <div class="icons">
                    <i class="fas fa-shipping-fast"></i>
                    <span>fast delivery</span>
                </div>
                <div class="icons">
                    <i class="fas fa-dollar-sign"></i>
                    <span>easy payments</span>
                </div>
                <div class="icons">
                    <i class="fas fa-headset"></i>
                   <a href="#"><span>24/7 service</span></a>
                </div>
            </div>
            <a href="{% url 'pages:about_us' %}" class="btn-about">Who We Are</a>
        </div>


    </div>



</section>

{% endblock content %}

templates/about_us.html
{% extends 'base/base.html' %} 

{% block content %}

 {% load static %}
<style>
body{
  background-color:#fcfcff;
}
</style>

<div class="container" style="margin-top: 15rem">
  <div class="row justify-content-md-left" >
    <h1 class="about-title h1">About Us</h1>

    <div class="col" style="margin-top: 20px">
      <div style="border-left: 6px solid; height: fit-content">
        <p class="h4" style="margin-left: 8px">
          In order to undertake, we, DreamTech, decided to create our work tool
          itself, in which it united the individual objective of each one and
          the objective of Entra21. From this, we have developed an e-commerce
          ,a virtual platform for sales, focused on the distribution of beverages local and
          national. Aiming to reach those who enjoy leisure accompanied by a
          good drink, we decided to simplify this process of discovery of new
          flavors and their acquisition. EasyDrink seeks present to the consumer
          the best in the beverage market, making life even more joyful.
        </p>
      </div>
      
   <a href="https://github.com/eduardasneves18/EasyDrink/blob/main/README.md">
  <button  class="btn btn-warning btn-lg active" type="button">
  Get to Know our work
  </button>
  </a>
  </div>
  

    <div class="col" style="margin-top: -180">
      <img src="{% static 'images/DreamTech.gif'%}" style="background-color:transparent" alt="" />
    </div>
  </div>
  
</div>


{% endblock %}

templates/contacts.html
{% extends 'base/base_home.html' %}

{% block content%}



<div class="container">
    <div class="row">
        <div class="col-6">
            <iframe
                src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d13249.247068040606!2d151.20960562674117!3d-33.8816236491114!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1spt-BR!2sbr!4v1468899355787"
                width="100%" height="100%" hea allowfullscreen>
            </iframe>
        </div>
        <div class="col-6">
            <div class="contact-form">
                <h2>Contact Us</h2>
            </div>
            <div class="contact-form">
                <h5>We are here assist you.</h5>
            </div>

            <form>
                <div class="mb-3">
                    <label for="name" class="form-label"></label>
                    <input type="email" class="form-control" placeholder="Name" id="1">
                </div>
                <div class="mb-3">
                    <label for="Email" class="form-label"></label>
                    <input type="email" class="form-control" placeholder="Email" id="2">
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>

                <div class="mb-3">
                    <label for="message"></label>
                    <textarea class="form-control" placeholder="Message" id="3" rows="5"></textarea>
                </div>

                <div class="mb-3">
                    <button type="button" class="btn btn-primary t">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content%}

templates/home.html
{% extends 'base/base_home.html'%}
{% load static %} 
{% block content %} 
{% include 'slider.html' %}


<style>
body{ text-transform: capitalize;}
</style>
<!-- Wines -->

<section class="dishes" id="dishes">
  <h3 class="sub-heading">our wines</h3>
  <h1 class="heading">popular wines</h1>
                                  
  
  <div class="box-container" style="height: fit-content">
    {% for key in data %} 
      {% if forloop.counter < 7 %}
    <div class="box" style="border:transparent">
      <a href="{{product.my_absolute_url }}" class="fas fa-heart"></a>
      <a href="{{key.my_absolute_url }}" class="fas fa-eye"></a>

      <a href="{{product.my_absolute_url }}"><img src="{{key.image}}" alt="{{key.description}}" /></a>
      <h3>{{key.title|slice:14}}</h3>

      <div class="stars">
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star"></i>
        <i class="fas fa-star-half-alt"></i>
      </div>
      <span>$ {{key.price}}</span><br>
       <form  method="post">
      <a href="{{key.my_absolute_url}}" class="btn" method="post" >Add to cart</a>

    </div>
      {% endif %}
    {% endfor %} 
    

</section>

<!-- Specials -->
<section class="menu" id="menu" style="background-color: rgb(226, 216, 216)">
  <h3 class="sub-heading">our wines menu</h3>
  <h1 class="heading">today's speciality</h1>
  
  <div class="box-container">
    {% for key in data %} 
      {% if forloop.counter < 7 %}
    <div class="box " style="border:transparent;">
      <div class="image"> 
        <img class="speciality_menu"src="{{key.image}}" style="width: 100px; margin: 0 0 0 82px;"alt="" />
        <a href="{{key.my_absolute_url}}" class="fas fa-heart"></a>
      </div>
      <center>
      <div class="content">
        <div class="stars">
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i>
          <i class="fas fa-star"></i> 
          <i class="fas fa-star-half-alt"></i>
        </div>
        <h3>{{key.title|slice:14}}</h3>
        <p>
          {{key.description|slice:"24"}}
        </p>
        <span class="price">$ {{key.price}}</span><br>
        <a href="{{key.my_absolute_url}}" class="btn">
          Add to cart
        </a>
      </div>
      </center>
    </div>
      {% endif %}
    {% endfor %}

  </div>
</section>

{% endblock content%}

templates/orders.html
{%extends 'base/base.html'%}

{%block content %}

{%endblock content%}

templates/pagination.html
  
<div>
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    Página {{ page.number }} de {{ page.paginator.num_pages }}.
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Próxima</a>
    {% endif %}
</div>

templates/slider.html
{% load static %}
<div id="app"></div>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/17.0.1/umd/react.production.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/17.0.1/umd/react-dom.production.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/classnames/2.2.6/index.min.js"></script>
<script type="text/javascript" src="{% static 'js/script_slider.js'%}"></script>

templates/wishes_list.html
{% extends 'base/base.html' %}

{% block content %}

{% endblock content %}