carts/urls.py
   
from django.urls import include, path
from rest_framework import routers
from . import views
from .views import checkout

router = routers.DefaultRouter()
router.register('', views.CartViewSet)
router.register('delivery-cost', views.DeliveryCostViewSet)

urlpatterns = [
    path('checkout',checkout, name="checkout"),
    path('', include((router.urls, 'shopping_cart_api.cart'))),
]

easydrink/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
   openapi.Info(
      title="Easy Drink",
      default_version='v1',
      description="Easy drink application",
    #   terms_of_service="https://www.google.com/policies/terms/",
    #   contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    # Documentation
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),


    #API endpoints
    path('api/v1/auth/', include ('users.urls')),
    path('api/v1/products/', include('products.urls')),
    path('api/v1/carts/', include('carts.urls')), 
    path('api/v1/discounts/', include('discounts.urls')), 
    path('api/v1/search/', include("search.urls")),
    

    #frontend
    path('', include('pages.urls'))

] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path

from .views import buy, get_products_category, AboutPageView, ContactsPageView, WishesPageView, OrdersPageView, LoginCartPageView,  home_page, get_cart, get_products, get_product_detail, post_register, post_reset_password, post_login,template_payment,favorite_products, about_us

app_name = "pages"

urlpatterns = [
    path("", home_page, name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("contacts/", ContactsPageView.as_view(), name="contacts"),
    path("wishes/", WishesPageView.as_view(), name="wishes"),
    path("orders/", OrdersPageView.as_view(), name="orders"),
    path("login_cart/",  LoginCartPageView.as_view(), name="login_cart"),
    path("products/", get_products, name="products"),
    path(r'products/category/<str:id>/', get_products_category, name='products_category'),
    path("products/<str:pk>/",get_product_detail, name="product_detail"),
    path("product-buy/",buy, name="buy"),
    path("cart/", get_cart, name="cart"),
    path("login/", post_login, name="login"),
    path("register/", post_register, name="register"),
    path("reset-password/", post_reset_password, name="reset-password"),
    path("payments/",template_payment, name="payments"),
    path("favorites/",favorite_products, name="favorites"),
    path("about_us/", about_us, name="about_us"),
    ]

users/urls.py
from django.urls import path
from .views import RegisterView, VerifyEmail, LoginAPIView, PasswordTokenCheckAPI, LogoutAPIView, SetNewPasswordAPIView, RequestPasswordResetEmail
from rest_framework_simplejwt.views import (TokenRefreshView,)

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginAPIView.as_view(), name="login"),
    path('email-verify/', VerifyEmail.as_view(), name="email-verify"),
    path('logout/', LogoutAPIView.as_view(), name="logout"),
    path('token/refresh/', TokenRefreshView.as_view(), name='token-refresh'),
    path('request-reset-email/', RequestPasswordResetEmail.as_view(), name="request-reset-email"),
    path('password-reset/<uidb64>/<token>/',PasswordTokenCheckAPI.as_view(), name='password-reset-confirm'),
    path('password-reset-complete', SetNewPasswordAPIView.as_view(), name='password-reset-complete')
]

users/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from django.db.models import base
from rest_framework_simplejwt.tokens import RefreshToken, Token


class UserManager(BaseUserManager):

    def create_user(self, username, email, password=None):
        if username is None:
            raise TypeError('Users should have a username')
        if email is None:
            raise TypeError('Users should have a Email')

        user = self.model(username=username, email=self.normalize_email(email))
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, email, password=None):
        if password is None:
            raise TypeError('Password should not be none')

        user = self.create_user(username, email, password)
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user


AUTH_PROVIDERS = {'facebook': 'facebook', 'google': 'google',
                  'twitter': 'twitter', 'email': 'email'}

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True, db_index=True)
    email = models.EmailField(max_length=255, unique=True, db_index=True)
    featured_image = models.ImageField(null = True, blank = True, default='default.jpg') #Usuário poderá colocar foto de perfil com este
    is_verified = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    birth_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True) #campo para saber quando um usuário foi criado, para isso usei o 'adicionar automaticamnte'.
    updated_at = models.DateTimeField(auto_now=True) # campo para saber quando fez uma atualização, para isso usei o 'automaticamente agora'.
    auth_provider = models.CharField(
        max_length=255, blank=False,
        null=False, default=AUTH_PROVIDERS.get('email'))


    USERNAME_FIELD = 'email' #definindo qual vai ser o capo que vai ser utilizado para fazer o login.
    REQUIRED_FIELDS = ['username'] #designando qual campo é obrigatório 

    objects = UserManager() # aqui vamos dar o comando de como gerenciar objetos do tipo acima, instanciando a classe gerente.

    def __str__(self):
        return self.email


    # metodo utilizado para que se torne possível obter os detalhes do usuário, capaz de fazer tokens de usuários
    def tokens(self):
        refresh = RefreshToken.for_user(self) #variável para o token de atualização
        return {
            'refresh': str(refresh),
            'access': str(refresh.access_token)
        }

users/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponsePermanentRedirect
from django.utils.encoding import smart_str, smart_bytes, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.shortcuts import render

from rest_framework import generics, status, views, permissions
from rest_framework.response import Response
from rest_framework_simplejwt.tokens import RefreshToken #token de atualização
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi

from .serializers import RegisterSerializer, SetNewPasswordSerializer, ResetPasswordEmailRequestSerializer, EmailVerificationSerializer, LoginSerializer, LogoutSerializer
from .models import User
from .utils import Util # aqui estou importando os dados do arquivo para que exerça as funçoes lá descritas.
from .renderers import UserRenderer
import jwt
import os
import requests
import random
import string


register = False

class CustomRedirect(HttpResponsePermanentRedirect):
    allowed_schemes = [os.environ.get('APP_SCHEME'), 'http', 'https']

# modo de exibição de API genérico
class RegisterView(generics.GenericAPIView):

    # campos resposáveis por enviar as informções para serializers.py
    serializer_class = RegisterSerializer

    renderer_classes = (UserRenderer,)

    # metodo para fazer a solicitação de postagem
    def post(self, request):
        user = request.data
        serializer = self.serializer_class(data=user) # responsável por enviar os dados para serializer.py
        serializer.is_valid(raise_exception=True) 
        serializer.save()

        user_data = serializer.data
        user = User.objects.get(email=user_data['email'])
        token = RefreshToken.for_user(user).access_token # onde se gera o token de acesso


        current_site = get_current_site(request).domain
        relativeLink = reverse('email-verify') # aqui recebe o link que foi revertido
        absurl = 'http://'+current_site+relativeLink+"?token="+str(token) # absolute url, aqui recebo apena o token de acesso como determinado acima
        email_body = 'Hi '+user.username + \
            '. Use the link below to verify your email \n' + absurl

        Util.send_email('Verification email', email_body, user.email)

        # está retornando dados do usuário 
        return Response(user_data, status=status.HTTP_201_CREATED)


class VerifyEmail(views.APIView):
    serializer_class = EmailVerificationSerializer

    token_param_config = openapi.Parameter(
        'token', in_=openapi.IN_QUERY, description='Description', type=openapi.TYPE_STRING)


    @swagger_auto_schema(manual_parameters=[token_param_config]) # utilizado para especificar um paraqmetro manualmente.
    # método para pegar o token que foi enviado ao e-mail.
    def get(self, request):
        token = request.GET.get('token') # aqui o programa está fazendo a autenticação, identificando qual usuário esta realizando a confirmação atravez da assimilação do token.
        try:
            payload = jwt.decode(token, settings.SECRET_KEY)
            user = User.objects.get(id=payload['user_id']) # buscando os objetos por meio da id deles.
            if not user.is_verified:
                user.is_verified = True # definindo a verificação do usuário. Esse campo não é obtido por padrão, nesse caso foi definida no 'User models'.
                user.save() 
            return render(request, 'user/verify_confirmed_email.html', {'message': 'Successfully activated'}) 
        except jwt.ExpiredSignatureError as identifier:
            return render(request, 'user/verify_confirmed_email.html', {'message': 'Activation link expired'}) 
        except jwt.exceptions.DecodeError as identifier:
            return render(request, 'user/verify_confirmed_email.html', {'message': 'Invalid token'}) 

class LoginAPIView(generics.GenericAPIView):
    serializer_class = LoginSerializer

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response(serializer.data, status=status.HTTP_200_OK)


class RequestPasswordResetEmail(generics.GenericAPIView):
    serializer_class = ResetPasswordEmailRequestSerializer

    def generate_random_password(self):
        return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(6))

    def change_password(self, password, token, uidb64):
        try: 
            # get_host
            url = "http://127.0.0.1:8000/api/v1/auth/password-reset-complete"
            payload = {
                "password": password,
                "token": token,
                "uidb64": uidb64,
            }
            requests.patch(url, data=payload)
            return True
        except:
            return False

    def post(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)

        email = request.data.get('email', '')

        if User.objects.filter(email=email).exists():
            user = User.objects.get(email=email)
            uidb64 = urlsafe_base64_encode(smart_bytes(user.id))
            token = PasswordResetTokenGenerator().make_token(user)
            password = self.generate_random_password()

            if (user is not None and uidb64 is not None and token is not None):
                if self.change_password(password, token, uidb64) is True:
                    email_body = 'Hello, \n Password changes sucessful your new password is: {}'.format(password)
                else:
                    email_body = 'Hello, \n Password changes failed try again'

            Util.send_email('Reset password', email_body, user.email)
            return Response({'success': 'We have sent you a link to your e-mail with further informations !!!'}, status=status.HTTP_200_OK)
        else:
            return Response({'failed': 'E-mail not found !!!'}, status=status.HTTP_200_OK)

    


class PasswordTokenCheckAPI(generics.GenericAPIView):
    serializer_class = SetNewPasswordSerializer

    def get(self, request, uidb64, token):

        redirect_url = request.GET.get('redirect_url')

        try:
            id = smart_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(id=id)
           
            if not PasswordResetTokenGenerator().check_token(user, token):

                if redirect_url is not None and len(redirect_url) > 3:
                    return CustomRedirect(redirect_url+'?token_valid=False')
                else:
                    return CustomRedirect(os.environ.get('FRONTEND_URL', '')+'?token_valid=False')

            if redirect_url and len(redirect_url) > 3:
                return CustomRedirect(redirect_url+'?token_valid=True&message=Credentials Valid&uidb64='+uidb64+'&token='+token)
            else:
                return CustomRedirect(os.environ.get('FRONTEND_URL', '')+'?token_valid=False')

        except DjangoUnicodeDecodeError as identifier:
            try:
                if not PasswordResetTokenGenerator().check_token(user):
                    return CustomRedirect(redirect_url+'?token_valid=False')
                    
            except UnboundLocalError as e:
                return Response({'error': 'Token is not valid, please request a new one'}, status=status.HTTP_400_BAD_REQUEST)



class SetNewPasswordAPIView(generics.GenericAPIView):
    serializer_class = SetNewPasswordSerializer

    def patch(self, request):
        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response({'success': True, 'message': 'Password reset success'}, status=status.HTTP_200_OK)


class LogoutAPIView(generics.GenericAPIView):
    serializer_class = LogoutSerializer

    permission_classes = (permissions.IsAuthenticated,)

    def post(self, request):

        serializer = self.serializer_class(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(status=status.HTTP_204_NO_CONTENT)

templates/user/login.html
{%extends 'base/base.html'%}
{% load static %}

{%block content %}
{% load crispy_forms_tags %}
<link rel="stylesheet" href="{% static 'css/styles/style_login.css' %}" />

    <div class="login">
            <!--Login--> 
            <div class="box-login">
                <h1>Login</h1>
              
                    <form  method="POST" class="labels">
                        {% csrf_token %}
                        {{ login_form|crispy }}
                        <button class="btn btn-form" type="submit">Login</button>
                    </form>
            

                <div style="margin:10px">
                <p class="text-center">Forgot your password? <a href="{% url 'pages:reset-password' %}" class="link-login">Reset now</a>.</p>
                </div>
                <div style="margin:10px">
                    <p class="text-center">Don't have an account? <a href="{% url 'pages:register' %}"  class="link-login">Create an account</a>.</p>
                </div>

            </div>
    </div>
    
    <script src="{% static 'js/script_nav.js' %}"></script>

{%endblock content%}

templates/user/login_cart.html
{%extends 'base/base.html'%}
{% load static %}

{%block content %}

{% load crispy_forms_tags %}
    <div class="login-style-cart mg-tp">
            <!--Login--> 
            <div class="container py-5 login-text-center mg-tp">
                <h1>Cart</h1>
                <h3> You aren't logged, make your login to add items!</h3>
                <button class="btn btn-form" type="submit" onclick="window.location = {% url 'pages:login' %} ">Go to new login</button>
                
    </div>
    
    <script src="{% static 'js/script_nav.js' %}"></script>

{%endblock content%}

templates/user/logout.html
{%extends 'base/base.html'%}

{%block content %}

{%endblock content%}

templates/user/register.html
{%extends 'base/base.html'%}
{% load static %}

{% block content %}
    {% load crispy_forms_tags %}

    <div class="login">
        <div class="box-login">
            <h1>Register</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ register_form|crispy }}

                    <button class="btn btn-form" type="submit">Register</button>
                </form>
        </div>
    </div>
    
{% endblock content %}

templates/user/reset_password.html
{%extends 'base/base.html'%}
{% load static %}


{%block content %}

{% load crispy_forms_tags %}

    <div class="login">
        <div class="box-login">
            <h1>Reset password</h1>
            <h4> Send your e-mail to reset password </h4>
            <form method="POST">
                {% csrf_token %}
                {{ reset_password_form|crispy }}

                <button class="btn btn-form" type="submit">Reset password</button>
            </form>
        </div>
    </div>
    
    <script src="{% static 'js/script_nav.js' %}"></script>

{%endblock content%}

templates/user/reset_password_confirmed.html
{% extends 'base/base.html' %}

{% block title %} Reset Password {% endblock title %}

{% block content %}

<section class="about" id="verify-email">

    <h3 class="sub-heading"> Reset Password </h3>

    <div class="row">
        <div class="content verify-confirm-email">
            <h1> {{ message }}</h1>
            <center><a href="{% url 'pages:login' %}" class="btn">Login</a></center>
        </div>
    </div>

</section>

{% endblock content %}

templates/user/verify_confirmed_email.html
{% extends 'base/base.html' %}

{% block title %}Verify e-mail{% endblock title %}

{% block content %}

<section class="about" id="verify-email" style="margin: 10% auto 0; """>
    
    <h3 class="sub-heading"> Verify e-mail </h3>
    <div class="row">
        <div class="content verify-confirm-email">
            <h1> {{ message }}</h1>
            <center><a href="{% url 'pages:login' %}" class="btn">Login</a></center>
        </div>
    </div>

</section>

{% endblock content %}

templates/user/verify_email.html
{% extends 'base/base.html' %}
{%load static%}
{% block title %} Verify e-mail {% endblock title %}

{% block content %}

<section class="about" id="verify-email" style="margin: 10% auto 0; ">

    <h3 class="sub-heading"> Verify e-mail </h3>
    <img style="display:block; width: 50%;margin: auto;  "src="{% static 'images/Logo3.png' %}">
    <div class="row">
        <div class="content verify-confirm-email">
            <h1> Please verify your e-mail to complete your register!!!</h1>
        </div>
    </div>

</section>

{% endblock content %}